services:
  frontend:
    build: ./src/front-end
    ports:
      - '5173:80'
    depends_on:
      - backend
    volumes:
      - ./src/front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    networks:
      - ft_transcendence_net
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        tag: "frontend"
        syslog-format: "rfc5424"
    labels:
      service.name: "frontend"
      service.type: "web"
      app.component: "ui"

  backend:
    build:
      context: ./src/back-end
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - ft_transcendence_net
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:5000"
        tag: "backend"
        syslog-format: "rfc5424"
    labels:
      service.name: "backend"
      service.type: "api"
      app.component: "server"

volumes:
  sqlite-data:

networks:
  ft_transcendence_net:
    external: true