version: '3.8'

services:
  frontend:
    build: ./src/front-end
    ports:
      - '5173:80'  # Or '3000:3000' if using a dev server
    depends_on:
      - backend
    volumes:
      - ./src/front-end:/app  # <-- watch for changes
      - /app/node_modules     # Avoid overwriting node_modules

  backend:
    build:
      context: ./src/back-end
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    restart: unless-stopped

volumes:
  sqlite-data: