filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
          add_error_key: true
          when:
            has_fields: ['message']

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_cloud_metadata: ~
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
  
logging.level: info
logging.to_stderr: true
logging.metrics.enabled: false
