filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      labels.dedot: true
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true
      when:
        has_fields: ['message']
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_fields:
      target: ''
      fields:
        environment: development
  - drop_event:
      when:
        or:
          - contains:
              container.name: "elasticsearch"
          - contains:
              container.name: "kibana"
          - contains:
              container.name: "logstash"
          - contains:
              container.name: "filebeat"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_stderr: true
logging.metrics.enabled: false
